services:
  ecmwf-obs:
    container_name: ecmwf_obs
    build:
      context: .
    restart: ${RESTART_POLICY}
    command: sh -c "/wait && ./docker-entrypoint.sh && gunicorn --bind 0.0.0.0:8000 synop:app"
    volumes:
      - ${DATASETS_VOLUME}:/data/bufr
      - ${STATE_VOLUME}:/data/state
    environment:
      - DEBUG=False
      - LOG=${LOG}
      - WAIT_HOSTS=${WAIT_HOSTS}
      - WAIT_TIMEOUT=60
      - STATE_DIR=/data/state
      - DATASETS_DIR=/data/bufr
      - SQLALCHEMY_DATABASE_URI=${DATABASE_URI}
      - FLASK_APP=synop/__init__.py
    ports:
      - 8000
networks:
  default:
    name: ${AHW_DOCKER_NETWORK}
    external: true