services:
  ecmwf-obs:
    container_name: ecmwf_obs
    build:
      context: .
    restart: ${RESTART_POLICY}
    command: sh -c "/wait && ./docker-entrypoint.sh && gunicorn --bind 0.0.0.0:8000 synop:app"
    volumes:
      - ${DATASETS_VOLUME}:/data/bufr
      - ${STATE_VOLUME}:/data/state
    environment:
      - DEBUG=False
      - WAIT_HOSTS=ecmwf_db:5432
      - WAIT_TIMEOUT=60
      - STATE_DIR=/data/state
      - DATASETS_DIR=/data/bufr
      - SQLALCHEMY_DATABASE_URI=postgresql://${DB_USER}:${DB_PASSWORD}@ecmwf_db:5432/${DB_NAME}
      - FLASK_APP=synop/__init__.py
  ecmwf-db:
    image: postgis/postgis:14-master
    container_name: ecmwf_db
    restart: ${RESTART_POLICY}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432"