COUNTRIES = [
    {'name': 'Algeria', 'iso': 'DZA'},
    {'name': 'Angola', 'iso': 'AGO'},
    {'name': 'Benin', 'iso': 'BEN'},
    {'name': 'Botswana', 'iso': 'BWA'},
    {'name': 'Burkina Faso', 'iso': 'BFA'},
    {'name': 'Burundi', 'iso': 'BDI'},
    {'name': 'Cameroon', 'iso': 'CMR'},
    {'name': 'Cape Verde', 'iso': 'CPV'},
    {'name': 'Central African Republic', 'iso': 'CAF'},
    {'name': 'Chad', 'iso': 'TCD'},
    {'name': 'Comoros', 'iso': 'COM'},
    {'name': 'Republic of Congo', 'iso': 'COG'},
    {'name': "Côte d'Ivoire", 'iso': 'CIV'},
    {'name': 'Democratic Republic of the Congo', 'iso': 'COD'},
    {'name': 'Djibouti', 'iso': 'DJI'},
    {'name': 'Egypt', 'iso': 'EGY'},
    {'name': 'Equatorial Guinea', 'iso': 'GNQ'},
    {'name': 'Eritrea', 'iso': 'ERI'},
    {'name': 'Ethiopia', 'iso': 'ETH'},
    {'name': 'Gabon', 'iso': 'GAB'},
    {'name': 'Gambia', 'iso': 'GMB'},
    {'name': 'Ghana', 'iso': 'GHA'},
    {'name': 'Guinea', 'iso': 'GIN'},
    {'name': 'Guinea-Bissau', 'iso': 'GNB'},
    {'name': 'Kenya', 'iso': 'KEN'},
    {'name': 'Lesotho', 'iso': 'LSO'},
    {'name': 'Liberia', 'iso': 'LBR'},
    {'name': 'Libya', 'iso': 'LBY'},
    {'name': 'Madagascar', 'iso': 'MDG'},
    {'name': 'Malawi', 'iso': 'MWI'},
    {'name': 'Mali', 'iso': 'MLI'},
    {'name': 'Mauritania', 'iso': 'MRT'},
    {'name': 'Mauritius', 'iso': 'MUS'},
    {'name': 'Mayotte', 'iso': 'MYT'},
    {'name': 'Morocco', 'iso': 'MAR'},
    {'name': 'Mozambique', 'iso': 'MOZ'},
    {'name': 'Namibia', 'iso': 'NAM'},
    {'name': 'Niger', 'iso': 'NER'},
    {'name': 'Nigeria', 'iso': 'NGA'},
    {'name': 'Reunion', 'iso': 'REU'},
    {'name': 'Rwanda', 'iso': 'RWA'},
    {'name': 'São Tomé and Príncipe', 'iso': 'STP'},
    {'name': 'Senegal', 'iso': 'SEN'},
    {'name': 'Seychelles', 'iso': 'SYC'},
    {'name': 'Sierra Leone', 'iso': 'SLE'},
    {'name': 'Somalia', 'iso': 'SOM'},
    {'name': 'South Africa', 'iso': 'ZAF'},
    {'name': 'South Sudan', 'iso': 'SSD'},
    {'name': 'Sudan', 'iso': 'SDN'},
    {'name': 'Swaziland', 'iso': 'SWZ'},
    {'name': 'Tanzania', 'iso': 'TZA'},
    {'name': 'Togo', 'iso': 'TGO'},
    {'name': 'Tunisia', 'iso': 'TUN'},
    {'name': 'Uganda', 'iso': 'UGA'},
    {'name': 'Western Sahara', 'iso': 'ESH'},
    {'name': 'Zambia', 'iso': 'ZMB'},
    {'name': 'Zimbabwe', 'iso': 'ZWE'}
]
